start_region:
  min_limits:
    [
     0.37
    ,-0.7
    ,0.42

    ,0.0
    ,-0.5
    ,0.0

    ,-2.135398
    #,-0.0872665
    ]
  max_limits:
    [
     0.89
    ,0.0
    ,1.62

    ,0.0
    ,0.5
    ,3.14159265359

    ,0.564602
    #,-0.0872665
    ]


# preprocess_planner: ARAStar
preprocess_planner: RRTConnectkConfigDefault
